parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Controller\Web\QuoteWizardController:
        bind:
              string $projectDir: '%kernel.project_dir%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
